/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as WhoWeAreRouteImport } from './routes/who-we-are'
import { Route as SupportTeamRouteImport } from './routes/support-team'
import { Route as SponsorsRouteImport } from './routes/sponsors'
import { Route as OurImpactRouteImport } from './routes/our-impact'
import { Route as MeetNaeNaeRouteImport } from './routes/meet-nae-nae'
import { Route as EventsRouteImport } from './routes/events'
import { Route as DonateRouteImport } from './routes/donate'
import { Route as ContactRouteImport } from './routes/contact'
import { Route as CelebritySupportersRouteImport } from './routes/celebrity-supporters'
import { Route as IndexRouteImport } from './routes/index'
import { Route as InitiativesVisualImpairmentRouteImport } from './routes/initiatives.visual-impairment'
import { Route as InitiativesMentalHealthRouteImport } from './routes/initiatives.mental-health'
import { Route as InitiativesSlugRouteImport } from './routes/initiatives.$slug'

const WhoWeAreRoute = WhoWeAreRouteImport.update({
  id: '/who-we-are',
  path: '/who-we-are',
  getParentRoute: () => rootRouteImport,
} as any)
const SupportTeamRoute = SupportTeamRouteImport.update({
  id: '/support-team',
  path: '/support-team',
  getParentRoute: () => rootRouteImport,
} as any)
const SponsorsRoute = SponsorsRouteImport.update({
  id: '/sponsors',
  path: '/sponsors',
  getParentRoute: () => rootRouteImport,
} as any)
const OurImpactRoute = OurImpactRouteImport.update({
  id: '/our-impact',
  path: '/our-impact',
  getParentRoute: () => rootRouteImport,
} as any)
const MeetNaeNaeRoute = MeetNaeNaeRouteImport.update({
  id: '/meet-nae-nae',
  path: '/meet-nae-nae',
  getParentRoute: () => rootRouteImport,
} as any)
const EventsRoute = EventsRouteImport.update({
  id: '/events',
  path: '/events',
  getParentRoute: () => rootRouteImport,
} as any)
const DonateRoute = DonateRouteImport.update({
  id: '/donate',
  path: '/donate',
  getParentRoute: () => rootRouteImport,
} as any)
const ContactRoute = ContactRouteImport.update({
  id: '/contact',
  path: '/contact',
  getParentRoute: () => rootRouteImport,
} as any)
const CelebritySupportersRoute = CelebritySupportersRouteImport.update({
  id: '/celebrity-supporters',
  path: '/celebrity-supporters',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const InitiativesVisualImpairmentRoute =
  InitiativesVisualImpairmentRouteImport.update({
    id: '/initiatives/visual-impairment',
    path: '/initiatives/visual-impairment',
    getParentRoute: () => rootRouteImport,
  } as any)
const InitiativesMentalHealthRoute = InitiativesMentalHealthRouteImport.update({
  id: '/initiatives/mental-health',
  path: '/initiatives/mental-health',
  getParentRoute: () => rootRouteImport,
} as any)
const InitiativesSlugRoute = InitiativesSlugRouteImport.update({
  id: '/initiatives/$slug',
  path: '/initiatives/$slug',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/celebrity-supporters': typeof CelebritySupportersRoute
  '/contact': typeof ContactRoute
  '/donate': typeof DonateRoute
  '/events': typeof EventsRoute
  '/meet-nae-nae': typeof MeetNaeNaeRoute
  '/our-impact': typeof OurImpactRoute
  '/sponsors': typeof SponsorsRoute
  '/support-team': typeof SupportTeamRoute
  '/who-we-are': typeof WhoWeAreRoute
  '/initiatives/$slug': typeof InitiativesSlugRoute
  '/initiatives/mental-health': typeof InitiativesMentalHealthRoute
  '/initiatives/visual-impairment': typeof InitiativesVisualImpairmentRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/celebrity-supporters': typeof CelebritySupportersRoute
  '/contact': typeof ContactRoute
  '/donate': typeof DonateRoute
  '/events': typeof EventsRoute
  '/meet-nae-nae': typeof MeetNaeNaeRoute
  '/our-impact': typeof OurImpactRoute
  '/sponsors': typeof SponsorsRoute
  '/support-team': typeof SupportTeamRoute
  '/who-we-are': typeof WhoWeAreRoute
  '/initiatives/$slug': typeof InitiativesSlugRoute
  '/initiatives/mental-health': typeof InitiativesMentalHealthRoute
  '/initiatives/visual-impairment': typeof InitiativesVisualImpairmentRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/celebrity-supporters': typeof CelebritySupportersRoute
  '/contact': typeof ContactRoute
  '/donate': typeof DonateRoute
  '/events': typeof EventsRoute
  '/meet-nae-nae': typeof MeetNaeNaeRoute
  '/our-impact': typeof OurImpactRoute
  '/sponsors': typeof SponsorsRoute
  '/support-team': typeof SupportTeamRoute
  '/who-we-are': typeof WhoWeAreRoute
  '/initiatives/$slug': typeof InitiativesSlugRoute
  '/initiatives/mental-health': typeof InitiativesMentalHealthRoute
  '/initiatives/visual-impairment': typeof InitiativesVisualImpairmentRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/celebrity-supporters'
    | '/contact'
    | '/donate'
    | '/events'
    | '/meet-nae-nae'
    | '/our-impact'
    | '/sponsors'
    | '/support-team'
    | '/who-we-are'
    | '/initiatives/$slug'
    | '/initiatives/mental-health'
    | '/initiatives/visual-impairment'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/celebrity-supporters'
    | '/contact'
    | '/donate'
    | '/events'
    | '/meet-nae-nae'
    | '/our-impact'
    | '/sponsors'
    | '/support-team'
    | '/who-we-are'
    | '/initiatives/$slug'
    | '/initiatives/mental-health'
    | '/initiatives/visual-impairment'
  id:
    | '__root__'
    | '/'
    | '/celebrity-supporters'
    | '/contact'
    | '/donate'
    | '/events'
    | '/meet-nae-nae'
    | '/our-impact'
    | '/sponsors'
    | '/support-team'
    | '/who-we-are'
    | '/initiatives/$slug'
    | '/initiatives/mental-health'
    | '/initiatives/visual-impairment'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  CelebritySupportersRoute: typeof CelebritySupportersRoute
  ContactRoute: typeof ContactRoute
  DonateRoute: typeof DonateRoute
  EventsRoute: typeof EventsRoute
  MeetNaeNaeRoute: typeof MeetNaeNaeRoute
  OurImpactRoute: typeof OurImpactRoute
  SponsorsRoute: typeof SponsorsRoute
  SupportTeamRoute: typeof SupportTeamRoute
  WhoWeAreRoute: typeof WhoWeAreRoute
  InitiativesSlugRoute: typeof InitiativesSlugRoute
  InitiativesMentalHealthRoute: typeof InitiativesMentalHealthRoute
  InitiativesVisualImpairmentRoute: typeof InitiativesVisualImpairmentRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/who-we-are': {
      id: '/who-we-are'
      path: '/who-we-are'
      fullPath: '/who-we-are'
      preLoaderRoute: typeof WhoWeAreRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/support-team': {
      id: '/support-team'
      path: '/support-team'
      fullPath: '/support-team'
      preLoaderRoute: typeof SupportTeamRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sponsors': {
      id: '/sponsors'
      path: '/sponsors'
      fullPath: '/sponsors'
      preLoaderRoute: typeof SponsorsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/our-impact': {
      id: '/our-impact'
      path: '/our-impact'
      fullPath: '/our-impact'
      preLoaderRoute: typeof OurImpactRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/meet-nae-nae': {
      id: '/meet-nae-nae'
      path: '/meet-nae-nae'
      fullPath: '/meet-nae-nae'
      preLoaderRoute: typeof MeetNaeNaeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/events': {
      id: '/events'
      path: '/events'
      fullPath: '/events'
      preLoaderRoute: typeof EventsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/donate': {
      id: '/donate'
      path: '/donate'
      fullPath: '/donate'
      preLoaderRoute: typeof DonateRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/contact': {
      id: '/contact'
      path: '/contact'
      fullPath: '/contact'
      preLoaderRoute: typeof ContactRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/celebrity-supporters': {
      id: '/celebrity-supporters'
      path: '/celebrity-supporters'
      fullPath: '/celebrity-supporters'
      preLoaderRoute: typeof CelebritySupportersRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/initiatives/visual-impairment': {
      id: '/initiatives/visual-impairment'
      path: '/initiatives/visual-impairment'
      fullPath: '/initiatives/visual-impairment'
      preLoaderRoute: typeof InitiativesVisualImpairmentRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/initiatives/mental-health': {
      id: '/initiatives/mental-health'
      path: '/initiatives/mental-health'
      fullPath: '/initiatives/mental-health'
      preLoaderRoute: typeof InitiativesMentalHealthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/initiatives/$slug': {
      id: '/initiatives/$slug'
      path: '/initiatives/$slug'
      fullPath: '/initiatives/$slug'
      preLoaderRoute: typeof InitiativesSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  CelebritySupportersRoute: CelebritySupportersRoute,
  ContactRoute: ContactRoute,
  DonateRoute: DonateRoute,
  EventsRoute: EventsRoute,
  MeetNaeNaeRoute: MeetNaeNaeRoute,
  OurImpactRoute: OurImpactRoute,
  SponsorsRoute: SponsorsRoute,
  SupportTeamRoute: SupportTeamRoute,
  WhoWeAreRoute: WhoWeAreRoute,
  InitiativesSlugRoute: InitiativesSlugRoute,
  InitiativesMentalHealthRoute: InitiativesMentalHealthRoute,
  InitiativesVisualImpairmentRoute: InitiativesVisualImpairmentRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
